apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata: 
  name: update-deploy-tag
spec:
  entrypoint: git-pull
  arguments:
    parameters:
    - name: NEW_IMAGE
      value: docker.io/nightmar39/basic-flask-docker
    - name: NEW_TAG
      value: test
    - name: CD_REPO
      value: https://github.com/nightmar39/flask-k8s-basic.git
    - name: GIT_USER
      value: nightmar39
    - name: DEPLOYMENT_FILE
      value: deployment.yml
    - name: CONTAINER_NAME
      value: flask-server-simple
    - name: COMMITER_EMAIL
      value: anthonyzilla94@gmail.com
    - name: BRANCH
      value: csdp 
  templates:
    - name: git-pull
      inputs:
        parameters: 
          - name: NEW_IMAGE
          - name: NEW_TAG
          - name: CD_REPO
          - name: DEPLOYMENT_FILE
          - name: CONTAINER_NAME
          - name: COMMITER_EMAIL
          - name: BRANCH
          - name: GIT_USER
          - name: REPO_OWNER
          - name: REPO_NAME
      script:
        image: docker.io/nightmar39/git-yq
        command: [bash]
        env: 
          - name: GIT_TOKEN
            valueFrom: 
              secretKeyRef:
                name: github-token
                key: token
        source: |
          #!bin/bash 
          git config --global user.email "{{inputs.parameters.COMMITER_EMAIL}}"
          git clone -b "{{inputs.parameters.BRANCH}}" https://"{{inputs.parameters.GIT_USER}}":$GIT_TOKEN@github.com/"{{inputs.parameters.REPO_OWNER}}"/"{{inputs.parameters.REPO_NAME}}".git tmp 
          cd tmp 
          export ARTIFACT="{{inputs.parameters.NEW_IMAGE}}":"{{inputs.parameters.NEW_TAG}}"
          echo $ARTIFACT
          yq -i '(.spec.template.spec.containers[] | select(.name == "{{inputs.parameters.CONTAINER_NAME}}") | .image) = env(ARTIFACT) ' deployment.yml 
          git add "{{inputs.parameters.DEPLOYMENT_FILE}}"
          git commit -m 'updating tag to "{{inputs.parameters.NEW_IMAGE}}"'
          git push https://"{{inputs.parameters.GIT_USER}}":$GIT_TOKEN@github.com/"{{inputs.parameters.REPO_OWNER}}"/"{{inputs.parameters.REPO_NAME}}".git "{{inputs.parameters.BRANCH}}"